apiVersion: v1
entries:
  truenas-csi:
  - annotations:
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: 1.3.0
    created: "2026-09-04T14:52:00.175794537-04:00"
    description: CSI driver for TrueNAS SCALE, providing NFS, iSCSI and NVMe-oF/TCP
      persistent volumes
    digest: 8d8bf0f0831896f5b5a3f29b25f056c268a1b21154b80b7cb638f7c1e387d7c0
    home: https://github.com/truenas/truenas-csi
    keywords:
    - csi
    - storage
    - truenas
    - zfs
    - nfs
    - iscsi
    - nvme-of
    kubeVersion: '>=1.20.0-0'
    maintainers:
    - name: TrueNAS
      url: https://github.com/truenas/truenas-csi
    name: truenas-csi
    sources:
    - https://github.com/truenas/truenas-csi
    type: application
    urls:
    - https://raw.githubusercontent.com/truenas/truenas-csi/master/charts/truenas-csi-1.3.0.tgz
    version: 1.3.0
generated: "2026-09-04T14:52:00.173590084-04:00"
