# iSCSI StorageClass with CHAP authentication
# Provides secure iSCSI connections with username/password authentication
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-iscsi-secure
provisioner: csi.truenas.io
parameters:
  protocol: "iscsi"
  compression: "LZ4"
  volblocksize: "16K"
  iscsi.blocksize: "4096"
  # CHAP authentication credentials
  # Note: For production, consider using Kubernetes secrets
  iscsi.chapUser: "chapuser"
  iscsi.chapSecret: "chappassword123"  # Must be 12-16 characters
  # Mutual CHAP (optional) - target authenticates to initiator
  # iscsi.chapPeerUser: "peeruser"
  # iscsi.chapPeerSecret: "peerpassword123"
  # Restrict access to specific initiator IQNs (optional)
  # iscsi.initiators: "iqn.2024-01.com.example:node1,iqn.2024-01.com.example:node2"
  # Restrict access to specific networks (optional)
  # iscsi.networks: "10.0.0.0/8,192.168.0.0/16"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
