apiVersion: v1
kind: ServiceAccount
metadata:
  name: truenas-csi-controller-sa
  namespace: {{ include "truenas-csi.namespace" . }}
  labels:
    {{- include "truenas-csi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: truenas-csi-node-sa
  namespace: {{ include "truenas-csi.namespace" . }}
  labels:
    {{- include "truenas-csi.labels" . | nindent 4 }}
